### ISSUE TITLE
save session id in redis

### ISSUE THREAD

**Issue by njustus** [THM-MoTE/webmodelica#66]
.. and not in memory. The SessionService is already stateless so no need to save the reference.

Not only save the session id, save the mope endpoint address too.. So there is no need for a name service (#67) because the address is already known:

save at `webmodelica::sessions::1234-5678-78901`
```yaml
id: 1234-5678-78901
project-id: 98
project-path: http://mope-service-1:9020/mope/project/98
```
